// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/swarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MasterからWorkerへの命令
type MasterCmd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*MasterCmd_Start
	//	*MasterCmd_Stop
	//	*MasterCmd_Quit
	Cmd           isMasterCmd_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterCmd) Reset() {
	*x = MasterCmd{}
	mi := &file_proto_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterCmd) ProtoMessage() {}

func (x *MasterCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterCmd.ProtoReflect.Descriptor instead.
func (*MasterCmd) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *MasterCmd) GetCmd() isMasterCmd_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *MasterCmd) GetStart() *StartCmd {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCmd_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *MasterCmd) GetStop() *StopCmd {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCmd_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *MasterCmd) GetQuit() *QuitCmd {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCmd_Quit); ok {
			return x.Quit
		}
	}
	return nil
}

type isMasterCmd_Cmd interface {
	isMasterCmd_Cmd()
}

type MasterCmd_Start struct {
	Start *StartCmd `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // テスト開始命令
}

type MasterCmd_Stop struct {
	Stop *StopCmd `protobuf:"bytes,2,opt,name=stop,proto3,oneof"` // テスト停止命令
}

type MasterCmd_Quit struct {
	Quit *QuitCmd `protobuf:"bytes,3,opt,name=quit,proto3,oneof"` // アプリ終了命令
}

func (*MasterCmd_Start) isMasterCmd_Cmd() {}

func (*MasterCmd_Stop) isMasterCmd_Cmd() {}

func (*MasterCmd_Quit) isMasterCmd_Cmd() {}

// WorkerからMasterへのメッセージ
type WorkerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMsg_Register
	//	*WorkerMsg_Stats
	//	*WorkerMsg_Finish
	Msg           isWorkerMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMsg) Reset() {
	*x = WorkerMsg{}
	mi := &file_proto_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMsg) ProtoMessage() {}

func (x *WorkerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMsg.ProtoReflect.Descriptor instead.
func (*WorkerMsg) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerMsg) GetMsg() isWorkerMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMsg) GetRegister() *RegisterMsg {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMsg_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMsg) GetStats() *StatsMsg {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMsg_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *WorkerMsg) GetFinish() *FinishMsg {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMsg_Finish); ok {
			return x.Finish
		}
	}
	return nil
}

type isWorkerMsg_Msg interface {
	isWorkerMsg_Msg()
}

type WorkerMsg_Register struct {
	Register *RegisterMsg `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // 最初の挨拶（スペック情報など）
}

type WorkerMsg_Stats struct {
	Stats *StatsMsg `protobuf:"bytes,2,opt,name=stats,proto3,oneof"` // 途中経過（RPSなど）
}

type WorkerMsg_Finish struct {
	Finish *FinishMsg `protobuf:"bytes,3,opt,name=finish,proto3,oneof"` // 完了報告
}

func (*WorkerMsg_Register) isWorkerMsg_Msg() {}

func (*WorkerMsg_Stats) isWorkerMsg_Msg() {}

func (*WorkerMsg_Finish) isWorkerMsg_Msg() {}

// 詳細なデータ構造定義
type StartCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl     string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	TotalRequests int32                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"` // Workerごとの割当量
	Concurrency   int32                  `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCmd) Reset() {
	*x = StartCmd{}
	mi := &file_proto_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCmd) ProtoMessage() {}

func (x *StartCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCmd.ProtoReflect.Descriptor instead.
func (*StartCmd) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *StartCmd) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *StartCmd) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StartCmd) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type StopCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCmd) Reset() {
	*x = StopCmd{}
	mi := &file_proto_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCmd) ProtoMessage() {}

func (x *StopCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCmd.ProtoReflect.Descriptor instead.
func (*StopCmd) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{3}
}

type QuitCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitCmd) Reset() {
	*x = QuitCmd{}
	mi := &file_proto_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitCmd) ProtoMessage() {}

func (x *QuitCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitCmd.ProtoReflect.Descriptor instead.
func (*QuitCmd) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{4}
}

type RegisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuArch       string                 `protobuf:"bytes,2,opt,name=cpu_arch,json=cpuArch,proto3" json:"cpu_arch,omitempty"` // "arm64", "amd64" など（デバッグ用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	mi := &file_proto_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterMsg) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterMsg) GetCpuArch() string {
	if x != nil {
		return x.CpuArch
	}
	return ""
}

type StatsMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,2,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	CurrentRps    float64                `protobuf:"fixed64,3,opt,name=current_rps,json=currentRps,proto3" json:"current_rps,omitempty"` // リアルタイムRPS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsMsg) Reset() {
	*x = StatsMsg{}
	mi := &file_proto_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsMsg) ProtoMessage() {}

func (x *StatsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsMsg.ProtoReflect.Descriptor instead.
func (*StatsMsg) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *StatsMsg) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *StatsMsg) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *StatsMsg) GetCurrentRps() float64 {
	if x != nil {
		return x.CurrentRps
	}
	return 0
}

type FinishMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalDurationMs int32                  `protobuf:"varint,1,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FinishMsg) Reset() {
	*x = FinishMsg{}
	mi := &file_proto_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMsg) ProtoMessage() {}

func (x *FinishMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMsg.ProtoReflect.Descriptor instead.
func (*FinishMsg) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *FinishMsg) GetTotalDurationMs() int32 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

var File_proto_swarm_proto protoreflect.FileDescriptor

const file_proto_swarm_proto_rawDesc = "" +
	"\n" +
	"\x11proto/swarm.proto\x12\x05proto\"\x87\x01\n" +
	"\tMasterCmd\x12'\n" +
	"\x05start\x18\x01 \x01(\v2\x0f.proto.StartCmdH\x00R\x05start\x12$\n" +
	"\x04stop\x18\x02 \x01(\v2\x0e.proto.StopCmdH\x00R\x04stop\x12$\n" +
	"\x04quit\x18\x03 \x01(\v2\x0e.proto.QuitCmdH\x00R\x04quitB\x05\n" +
	"\x03cmd\"\x99\x01\n" +
	"\tWorkerMsg\x120\n" +
	"\bregister\x18\x01 \x01(\v2\x12.proto.RegisterMsgH\x00R\bregister\x12'\n" +
	"\x05stats\x18\x02 \x01(\v2\x0f.proto.StatsMsgH\x00R\x05stats\x12*\n" +
	"\x06finish\x18\x03 \x01(\v2\x10.proto.FinishMsgH\x00R\x06finishB\x05\n" +
	"\x03msg\"r\n" +
	"\bStartCmd\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x05R\rtotalRequests\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\x05R\vconcurrency\"\t\n" +
	"\aStopCmd\"\t\n" +
	"\aQuitCmd\"E\n" +
	"\vRegisterMsg\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x19\n" +
	"\bcpu_arch\x18\x02 \x01(\tR\acpuArch\"o\n" +
	"\bStatsMsg\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x02 \x01(\x05R\tfailCount\x12\x1f\n" +
	"\vcurrent_rps\x18\x03 \x01(\x01R\n" +
	"currentRps\"7\n" +
	"\tFinishMsg\x12*\n" +
	"\x11total_duration_ms\x18\x01 \x01(\x05R\x0ftotalDurationMs2A\n" +
	"\fSwarmService\x121\n" +
	"\aConnect\x12\x10.proto.WorkerMsg\x1a\x10.proto.MasterCmd(\x010\x01B$Z\"github.com/ryokotaka/SwarmGo/protob\x06proto3"

var (
	file_proto_swarm_proto_rawDescOnce sync.Once
	file_proto_swarm_proto_rawDescData []byte
)

func file_proto_swarm_proto_rawDescGZIP() []byte {
	file_proto_swarm_proto_rawDescOnce.Do(func() {
		file_proto_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swarm_proto_rawDesc), len(file_proto_swarm_proto_rawDesc)))
	})
	return file_proto_swarm_proto_rawDescData
}

var file_proto_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_swarm_proto_goTypes = []any{
	(*MasterCmd)(nil),   // 0: proto.MasterCmd
	(*WorkerMsg)(nil),   // 1: proto.WorkerMsg
	(*StartCmd)(nil),    // 2: proto.StartCmd
	(*StopCmd)(nil),     // 3: proto.StopCmd
	(*QuitCmd)(nil),     // 4: proto.QuitCmd
	(*RegisterMsg)(nil), // 5: proto.RegisterMsg
	(*StatsMsg)(nil),    // 6: proto.StatsMsg
	(*FinishMsg)(nil),   // 7: proto.FinishMsg
}
var file_proto_swarm_proto_depIdxs = []int32{
	2, // 0: proto.MasterCmd.start:type_name -> proto.StartCmd
	3, // 1: proto.MasterCmd.stop:type_name -> proto.StopCmd
	4, // 2: proto.MasterCmd.quit:type_name -> proto.QuitCmd
	5, // 3: proto.WorkerMsg.register:type_name -> proto.RegisterMsg
	6, // 4: proto.WorkerMsg.stats:type_name -> proto.StatsMsg
	7, // 5: proto.WorkerMsg.finish:type_name -> proto.FinishMsg
	1, // 6: proto.SwarmService.Connect:input_type -> proto.WorkerMsg
	0, // 7: proto.SwarmService.Connect:output_type -> proto.MasterCmd
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_swarm_proto_init() }
func file_proto_swarm_proto_init() {
	if File_proto_swarm_proto != nil {
		return
	}
	file_proto_swarm_proto_msgTypes[0].OneofWrappers = []any{
		(*MasterCmd_Start)(nil),
		(*MasterCmd_Stop)(nil),
		(*MasterCmd_Quit)(nil),
	}
	file_proto_swarm_proto_msgTypes[1].OneofWrappers = []any{
		(*WorkerMsg_Register)(nil),
		(*WorkerMsg_Stats)(nil),
		(*WorkerMsg_Finish)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swarm_proto_rawDesc), len(file_proto_swarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_swarm_proto_goTypes,
		DependencyIndexes: file_proto_swarm_proto_depIdxs,
		MessageInfos:      file_proto_swarm_proto_msgTypes,
	}.Build()
	File_proto_swarm_proto = out.File
	file_proto_swarm_proto_goTypes = nil
	file_proto_swarm_proto_depIdxs = nil
}
