// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/swarm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwarmService_Connect_FullMethodName = "/proto.SwarmService/Connect"
)

// SwarmServiceClient is the client API for SwarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 1. Worker -> Master への登録・報告サービス
type SwarmServiceClient interface {
	// WorkerがMasterに接続し、双方向ストリーミングを開始する
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMsg, MasterCmd], error)
}

type swarmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwarmServiceClient(cc grpc.ClientConnInterface) SwarmServiceClient {
	return &swarmServiceClient{cc}
}

func (c *swarmServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMsg, MasterCmd], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SwarmService_ServiceDesc.Streams[0], SwarmService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMsg, MasterCmd]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwarmService_ConnectClient = grpc.BidiStreamingClient[WorkerMsg, MasterCmd]

// SwarmServiceServer is the server API for SwarmService service.
// All implementations must embed UnimplementedSwarmServiceServer
// for forward compatibility.
//
// 1. Worker -> Master への登録・報告サービス
type SwarmServiceServer interface {
	// WorkerがMasterに接続し、双方向ストリーミングを開始する
	Connect(grpc.BidiStreamingServer[WorkerMsg, MasterCmd]) error
	mustEmbedUnimplementedSwarmServiceServer()
}

// UnimplementedSwarmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwarmServiceServer struct{}

func (UnimplementedSwarmServiceServer) Connect(grpc.BidiStreamingServer[WorkerMsg, MasterCmd]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSwarmServiceServer) mustEmbedUnimplementedSwarmServiceServer() {}
func (UnimplementedSwarmServiceServer) testEmbeddedByValue()                      {}

// UnsafeSwarmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwarmServiceServer will
// result in compilation errors.
type UnsafeSwarmServiceServer interface {
	mustEmbedUnimplementedSwarmServiceServer()
}

func RegisterSwarmServiceServer(s grpc.ServiceRegistrar, srv SwarmServiceServer) {
	// If the following call panics, it indicates UnimplementedSwarmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwarmService_ServiceDesc, srv)
}

func _SwarmService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwarmServiceServer).Connect(&grpc.GenericServerStream[WorkerMsg, MasterCmd]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwarmService_ConnectServer = grpc.BidiStreamingServer[WorkerMsg, MasterCmd]

// SwarmService_ServiceDesc is the grpc.ServiceDesc for SwarmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwarmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SwarmService",
	HandlerType: (*SwarmServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SwarmService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/swarm.proto",
}
